### ISSUE TITLE
`embedRelease` or `embedDebug` buildType or productFlavours support

### ISSUE THREAD

**Issue by mochadwi** [kezong/fat-aar-android#46]
Does it currently support different both buildTypes & productFlavours? @kezong

**Comment by kezong** [comment]
Flavor is supported, you can build in `assembleFlavorRelease` or `assembleFlavor2Debug`, but for the time it is not supported to write like 
`flavorEmbed 'com.facebook.fresco:fresco:1.11.0'`

**Comment by mochadwi** [comment]
I see, awesome. But like you stated above, currently, we can't use `buildTypes or buildFlavours` for  `embed` keywords.

With the general `assemble[WithFlavour&BuildType]` the aar merging can't be processed, right?

**Comment by kezong** [comment]
With the general `assemble[WithFlavour&BuildType]`,  aar can be merged, and it is merged according to the customized of flavor & build type of each module.

**Comment by mochadwi** [comment]
My apologies look like I've been mistaken.

What I mean was, e.g:
`embedDebug example:library:1.0.0-debug`



> Flavor is supported, you can build in `assembleFlavorRelease` or `assembleFlavor2Debug`, but for the time it is not supported to write like
> `flavorEmbed 'com.facebook.fresco:fresco:1.11.0'`

As stated in your statement above. So the workaround will be using traditional approach e.g:
`implementationDebug example:library:1.0.0-debug` or

`implementationRelease example:library:1.0.0-debug`

**Comment by kezong** [comment]
Sorry, I don't quite understand.
Do you mean `debugImplementation` or `releaseImplementaion` ?
For the time `debugEmbed` or `releaseEmbed` is not supported, if you write like this, will resulting a compile error.

**Comment by mochadwi** [comment]
> Sorry, I don't quite understand.
Yes, sorry for the typo. 

> Do you mean `debugImplementation` or `releaseImplementaion` ?
What I mean was `[debug|release]Implementation`

> For the time `debugEmbed` or `releaseEmbed` is not supported, if you write like this, will resulting a compile error.
roger that.

**Comment by JirkaKrivanek** [comment]
Sorry, I am reading this thread third time and I am still confused, that is why I am trying to comment on it again...

Currently I have this in my gradle.build:
```
    debugImplementation 'com.gemalto.android.lib:http-real-debug:2.0.2'
    releaseImplementation 'com.gemalto.android.lib:http-real-release:2.0.2'
```

It is a MUST to have different dependency for debug resp. release (because the debug variant allows insecure HTTP connections while the release variant crashes on it).

Unfortunately, the http dependency is not embedded with the output AAR.

I would expect to be able to do something like this:
```
    debugEmbed 'com.gemalto.android.lib:http-real-debug:2.0.2'
    releaseEmbed 'com.gemalto.android.lib:http-real-release:2.0.2'
```

I already know that the intuitive way above does not work :)

From the thread above, I have a feeling that it actually is possible to achieve the effect somehow.

Could you please write a clear example for me?

**Comment by mochadwi** [comment]
No, it still not supported currently @JirkaKrivanek

**Comment by NMGuner** [comment]
Proposed a solution on #135 for build types and product flavors (only with single flavor dimension).
